/*
 * Globalize Culture or-IN
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "or-IN", "default", {
	name: "or-IN",
	englishName: "Oriya (India)",
	nativeName: "±®∏Ê±®∏Ê±®∏Ê (±®∏Ê±®∏Ê±®∏Ê)",
	language: "or",
	numberFormat: {
		groupSizes: [3,2],
		percent: {
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["$ -n","$ n"],
			groupSizes: [3,2],
			symbol: "‡¨ü"
		}
	},
	calendars: {
		standard: {
			"/": "-",
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê¨∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¨∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¨∞"],
				namesAbbr: ["±®∏Ê±®∏Êø.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê‡¨≥.","±®∏Ê±®∏Êß.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê‡¨∞.","±®∏Ê±®∏Êø."],
				namesShort: ["‡¨∞","±®∏Ê±®∏Êæ","‡¨Æ","±®∏Ê≠Å","±®∏Ê≠Å","±®∏Ê≠Å","‡¨∂"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞‡≠Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê≠Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êç\u200c","±®∏Ê≠á","±®∏Ê±®∏Ê±®∏Ê\u200c","±®∏Ê±®∏Ê±®∏Ê‡¨á","±®∏Ê±®∏Ê±®∏Ê‡¨ü","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê¨∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","(±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞‡≠Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê≠Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êç\u200c","±®∏Ê≠á","±®∏Ê±®∏Ê±®∏Ê\u200c","±®∏Ê±®∏Ê±®∏Ê‡¨á","±®∏Ê±®∏Ê±®∏Ê‡¨ü","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê¨∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","(±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""]
			},
			eras: [{"name":"±®∏Ê±®∏Ê∞‡≠Ä±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶","start":null,"offset":0}],
			patterns: {
				d: "dd-MM-yy",
				D: "dd MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "dd MMMM yyyy HH:mm",
				F: "dd MMMM yyyy HH:mm:ss",
				M: "dd MMMM"
			}
		}
	}
});

}( this ));
