/*
 * Globalize Culture th-TH
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "th-TH", "default", {
	name: "th-TH",
	englishName: "Thai (Thailand)",
	nativeName: "±®∏Ê±®∏Ê¢ (±®∏Ê±®∏Ê¢)",
	language: "th",
	numberFormat: {
		currency: {
			pattern: ["-$n","$n"],
			symbol: "‡∏ø"
		}
	},
	calendars: {
		standard: {
			name: "ThaiBuddhist",
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êå","±®∏Ê±®∏Ê±®∏Ê±®∏Êπå","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∏£","±®∏Ê±®∏Êò","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê‡πå","‡πÄ±®∏Ê±®∏Ê±®∏Ê"],
				namesAbbr: ["±®∏Ê∏≤.","‡∏à.","‡∏≠.","‡∏û.","±®∏Ê∏§.","‡∏®.","‡∏™."],
				namesShort: ["‡∏≠","‡∏à","‡∏≠","‡∏û","‡∏û","‡∏®","‡∏™"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê∏°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êπå","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∏°","‡πÄ±®∏Ê±®∏Ê±®∏Ê‡∏ô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∏°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∏ô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê°",""],
				namesAbbr: ["‡∏°.‡∏Ñ.","‡∏Å.‡∏û.","±®∏Ê∏µ.‡∏Ñ.","‡πÄ‡∏°.‡∏¢.","‡∏û.‡∏Ñ.","±®∏Ê∏¥.‡∏¢.","‡∏Å.‡∏Ñ.","‡∏™.‡∏Ñ.","‡∏Å.‡∏¢.","‡∏ï.‡∏Ñ.","‡∏û.‡∏¢.","‡∏ò.‡∏Ñ.",""]
			},
			eras: [{"name":"‡∏û.‡∏®.","start":null,"offset":-543}],
			twoDigitYearMax: 2572,
			patterns: {
				d: "d/M/yyyy",
				D: "d MMMM yyyy",
				t: "H:mm",
				T: "H:mm:ss",
				f: "d MMMM yyyy H:mm",
				F: "d MMMM yyyy H:mm:ss",
				M: "dd MMMM",
				Y: "MMMM yyyy"
			}
		},
		Gregorian_Localized: {
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êå","±®∏Ê±®∏Ê±®∏Ê±®∏Êπå","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∏£","±®∏Ê±®∏Êò","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê‡πå","‡πÄ±®∏Ê±®∏Ê±®∏Ê"],
				namesAbbr: ["±®∏Ê∏≤.","‡∏à.","‡∏≠.","‡∏û.","±®∏Ê∏§.","‡∏®.","‡∏™."],
				namesShort: ["‡∏≠","‡∏à","‡∏≠","‡∏û","‡∏û","‡∏®","‡∏™"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê∏°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êπå","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∏°","‡πÄ±®∏Ê±®∏Ê±®∏Ê‡∏ô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∏°","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∏ô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê°",""],
				namesAbbr: ["‡∏°.‡∏Ñ.","‡∏Å.‡∏û.","±®∏Ê∏µ.‡∏Ñ.","‡πÄ‡∏°.‡∏¢.","‡∏û.‡∏Ñ.","±®∏Ê∏¥.‡∏¢.","‡∏Å.‡∏Ñ.","‡∏™.‡∏Ñ.","‡∏Å.‡∏¢.","‡∏ï.‡∏Ñ.","‡∏û.‡∏¢.","‡∏ò.‡∏Ñ.",""]
			},
			patterns: {
				d: "d/M/yyyy",
				D: "'±®∏Ê±®∏Êô'dddd'±®∏Ê±®∏Êà' d MMMM yyyy",
				t: "H:mm",
				T: "H:mm:ss",
				f: "'±®∏Ê±®∏Êô'dddd'±®∏Ê±®∏Êà' d MMMM yyyy H:mm",
				F: "'±®∏Ê±®∏Êô'dddd'±®∏Ê±®∏Êà' d MMMM yyyy H:mm:ss",
				M: "dd MMMM",
				Y: "MMMM yyyy"
			}
		}
	}
});

}( this ));
