/*
 * Globalize Culture hi
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "hi", "default", {
	name: "hi",
	englishName: "Hindi",
	nativeName: "±®∏Ê±®∏Ê±®∏Ê‡•Ä",
	language: "hi",
	numberFormat: {
		groupSizes: [3,2],
		percent: {
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["$ -n","$ n"],
			groupSizes: [3,2],
			symbol: "±®∏Ê•Å"
		}
	},
	calendars: {
		standard: {
			"/": "-",
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞"],
				namesAbbr: ["±®∏Ê±®∏Êø.","±®∏Ê±®∏ÊÆ.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Êß.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê‡§∞.","±®∏Ê±®∏Êø."],
				namesShort: ["‡§∞","‡§∏","‡§Æ","‡§¨","‡§ó","‡§∂","‡§∂"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê‡•Ä","±®∏Ê±®∏Ê±®∏Ê‡•Ä","±®∏Ê±®∏Ê±®∏Ê‡§ö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§≤","±®∏Ê§à","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡§à","±®∏Ê±®∏Ê±®∏Ê‡§§","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞",""],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê‡•Ä","±®∏Ê±®∏Ê±®∏Ê‡•Ä","±®∏Ê±®∏Ê±®∏Ê‡§ö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§≤","±®∏Ê§à","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡§à","±®∏Ê±®∏Ê±®∏Ê‡§§","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞",""]
			},
			AM: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡§®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡§®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡§®"],
			PM: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®"],
			patterns: {
				d: "dd-MM-yyyy",
				D: "dd MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "dd MMMM yyyy HH:mm",
				F: "dd MMMM yyyy HH:mm:ss",
				M: "dd MMMM"
			}
		}
	}
});

}( this ));
