/*
 * Globalize Culture si
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "si", "default", {
	name: "si",
	englishName: "Sinhala",
	nativeName: "±®∏Ê±®∏Ê±®∏Ê‡∂Ω",
	language: "si",
	numberFormat: {
		groupSizes: [3,2],
		negativeInfinity: "-±®∏Ê±®∏Ê±®∏Ê±®∏Ê∂∫",
		positiveInfinity: "±®∏Ê±®∏Ê±®∏Ê±®∏Ê∂∫",
		percent: {
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["($ n)","$ n"],
			symbol: "±®∏Ê∑î."
		}
	},
	calendars: {
		standard: {
			"/": "-",
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê‡∑è","±®∏Ê±®∏Ê±®∏Ê‡∑è","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∑Ä±®∏Ê±®∏Êè","±®∏Ê±®∏Ê±®∏Ê‡∑è","±®∏Ê∑ä\u200d±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êè","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∑è"],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê‡∑è","±®∏Ê±®∏Ê±®∏Ê‡∑è","±®∏Ê±®∏Ê±®∏Ê‡∑è","±®∏Ê±®∏Ê±®∏Ê‡∑è","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∑è","±®∏Ê±®∏ÊÄ±®∏Ê±®∏Êè","±®∏Ê±®∏Ê±®∏Ê‡∑è"],
				namesShort: ["‡∂â","‡∑É","‡∂Ö","‡∂∂","±®∏Ê∑ä\u200d‡∂ª","±®∏Ê∑í","±®∏Ê∑ô"]
			},
			months: {
				names: ["±®∏Ê±®∏ÊÄ±®∏Ê±®∏Êí","±®∏Ê±®∏Ê±®∏Ê‡∑Ä±®∏Ê±®∏Êí","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∑î","‡∂Ö\u200c±®∏Ê∑ä\u200d±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","‡∂Ö\u200c±®∏Ê±®∏Ê±®∏Ê±®∏Ê∑î","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏ÊÄ±®∏Ê±®∏Ê±®∏Ê±®∏Ê∑ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∑ä",""],
				namesAbbr: ["±®∏Ê∂±.","±®∏Ê±®∏Ê∂.","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∑î.","±®∏Ê±®∏Êä\u200d±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Êù.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Êä.","±®∏Ê±®∏ÊÄ‡∑ê.","±®∏Ê±®∏Ê±®∏Ê.",""]
			},
			AM: ["±®∏Ê∑ô.‡∑Ä.","±®∏Ê∑ô.‡∑Ä.","±®∏Ê∑ô.‡∑Ä."],
			PM: ["‡∂¥.‡∑Ä.","‡∂¥.‡∑Ä.","‡∂¥.‡∑Ä."],
			eras: [{"name":"±®∏Ê∑ä\u200d±®∏Ê∑í.‡∑Ä.","start":null,"offset":0}],
			patterns: {
				d: "yyyy-MM-dd",
				D: "yyyy MMMM' ±®∏Ê∑É 'dd' ‡∑Ä±®∏Ê±®∏Ê±®∏Ê‡∑è 'dddd",
				f: "yyyy MMMM' ±®∏Ê∑É 'dd' ‡∑Ä±®∏Ê±®∏Ê±®∏Ê‡∑è 'dddd h:mm tt",
				F: "yyyy MMMM' ±®∏Ê∑É 'dd' ‡∑Ä±®∏Ê±®∏Ê±®∏Ê‡∑è 'dddd h:mm:ss tt",
				Y: "yyyy MMMM"
			}
		}
	}
});

}( this ));
