/*
 * Globalize Culture ta-IN
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "ta-IN", "default", {
	name: "ta-IN",
	englishName: "Tamil (India)",
	nativeName: "±®∏Ê±®∏Ê±®∏Ê‡Øç (±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êæ)",
	language: "ta",
	numberFormat: {
		groupSizes: [3,2],
		percent: {
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["$ -n","$ n"],
			groupSizes: [3,2],
			symbol: "±®∏ÊØÇ"
		}
	},
	calendars: {
		standard: {
			"/": "-",
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êà","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡Øà","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊØà","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡Øà","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊØà"],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê±®∏ÊØÅ","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê‡Øç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êç","±®∏Ê±®∏Ê±®∏Ê±®∏ÊÆø","±®∏Ê±®∏Êø"],
				namesShort: ["±®∏ÊÆæ","±®∏ÊÆø","±®∏ÊØÜ","±®∏ÊØÅ","±®∏ÊÆø","±®∏ÊØÜ","‡Æö"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê‡Æø","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏ÊØç","±®∏Ê±®∏Ê±®∏Ê±®∏ÊØç","±®∏ÊØá","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏ÊØç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊØç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê‡Æø","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏ÊØç","±®∏Ê±®∏Ê±®∏Ê±®∏ÊØç","±®∏ÊØá","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏ÊØç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊØç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""]
			},
			AM: ["±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê"],
			PM: ["±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê"],
			patterns: {
				d: "dd-MM-yyyy",
				D: "dd MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "dd MMMM yyyy HH:mm",
				F: "dd MMMM yyyy HH:mm:ss",
				M: "dd MMMM",
				Y: "MMMM yyyy"
			}
		}
	}
});

}( this ));
