/*
 * Globalize Culture lo-LA
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "lo-LA", "default", {
	name: "lo-LA",
	englishName: "Lao (Lao P.D.R.)",
	nativeName: "±®∏Ê±®∏Êß (‡∫™.‡∫õ.‡∫õ. ±®∏Ê±®∏Êß)",
	language: "lo",
	numberFormat: {
		pattern: ["(n)"],
		groupSizes: [3,0],
		percent: {
			groupSizes: [3,0]
		},
		currency: {
			pattern: ["(n$)","n$"],
			groupSizes: [3,0],
			symbol: "‚Ç≠"
		}
	},
	calendars: {
		standard: {
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∫ô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∫ô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∫î","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∫Å","±®∏Ê±®∏Êô‡ªÄ±®∏Ê±®∏Ê≤"],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê‡∫î","±®∏Ê±®∏Êô","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∫ô","±®∏Ê±®∏Êî","±®∏Ê±®∏Ê±®∏Ê‡∫î","±®∏Ê±®∏ÊÅ","‡ªÄ±®∏Ê±®∏Ê≤"],
				namesShort: ["‡∫≠","‡∫à","‡∫≠","‡∫û","‡∫û","‡∫™","‡ªÄ"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê∫ô","±®∏Ê±®∏Ê±®∏Ê‡∫≤","±®∏Ê±®∏Ê±®∏Ê","‡ªÄ±®∏Ê±®∏Ê≤","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê≤","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∫≤","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êî","±®∏Ê±®∏Ê±®∏Ê‡∫≤","±®∏Ê±®∏Ê±®∏Ê‡∫≤","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê‡∫Å","±®∏Ê±®∏Ê±®∏Ê‡∫≤",""],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê∫ô","±®∏Ê±®∏Ê±®∏Ê‡∫≤","±®∏Ê±®∏Ê±®∏Ê","‡ªÄ±®∏Ê±®∏Ê≤","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê≤","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∫≤","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êî","±®∏Ê±®∏Ê±®∏Ê‡∫≤","±®∏Ê±®∏Ê±®∏Ê‡∫≤","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê‡∫Å","±®∏Ê±®∏Ê±®∏Ê‡∫≤",""]
			},
			AM: ["‡ªÄ±®∏Ê±®∏Ê±®∏Ê","‡ªÄ±®∏Ê±®∏Ê±®∏Ê","‡ªÄ±®∏Ê±®∏Ê±®∏Ê"],
			PM: ["±®∏Ê±®∏Êá","±®∏Ê±®∏Êá","±®∏Ê±®∏Êá"],
			patterns: {
				d: "dd/MM/yyyy",
				D: "dd MMMM yyyy",
				t: "H:mm tt",
				T: "HH:mm:ss",
				f: "dd MMMM yyyy H:mm tt",
				F: "dd MMMM yyyy HH:mm:ss",
				M: "dd MMMM",
				Y: "MMMM yyyy"
			}
		}
	}
});

}( this ));
