/*
 * Globalize Culture as
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "as", "default", {
	name: "as",
	englishName: "Assamese",
	nativeName: "±®∏Ê±®∏ÊÆ‡ßÄ±®∏Ê¶æ",
	language: "as",
	numberFormat: {
		groupSizes: [3,2],
		"NaN": "nan",
		negativeInfinity: "-infinity",
		positiveInfinity: "infinity",
		percent: {
			pattern: ["-n%","n%"],
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["$ -n","n$"],
			groupSizes: [3,2],
			symbol: "‡¶ü"
		}
	},
	calendars: {
		standard: {
			"/": "-",
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Êß∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Êß∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Êß∞","±®∏Ê±®∏Ê±®∏Ê±®∏Êß∞"],
				namesAbbr: ["±®∏Ê±®∏ÊÆ.","±®∏Ê±®∏Ê±®∏Ê‡¶≤.","±®∏Ê±®∏Êß.","±®∏Ê±®∏Êπ.","±®∏Ê±®∏Ê±®∏Ê‡¶∞.","±®∏Ê±®∏Êø.","±®∏Ê±®∏Êø."],
				namesShort: ["±®∏Êßã","‡¶Æ","±®∏ÊßÅ","±®∏ÊßÉ","±®∏ÊßÅ","‡¶∂","‡¶∞"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞‡ßÄ","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊßÄ","±®∏Ê±®∏Ê±®∏Ê‡¶ö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶≤","±®∏Êßá","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡¶á","±®∏Ê±®∏Ê±®∏Ê‡¶ü","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏ÊßÅ","±®∏Ê±®∏Ê±®∏Ê‡¶ö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶≤","±®∏Êßá","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡¶á","±®∏Ê±®∏Ê±®∏Ê‡¶ü","±®∏Ê±®∏Ê±®∏Ê±®∏Êßá","±®∏Ê±®∏Ê±®∏Ê‡ßã","±®∏Ê±®∏Êá","±®∏Ê±®∏Ê±®∏Ê",""]
			},
			AM: ["±®∏Ê±®∏Ê±®∏Ê±®∏ÊßÅ","±®∏Ê±®∏Ê±®∏Ê±®∏ÊßÅ","±®∏Ê±®∏Ê±®∏Ê±®∏ÊßÅ"],
			PM: ["±®∏Ê±®∏Ê±®∏Ê‡¶ø","±®∏Ê±®∏Ê±®∏Ê‡¶ø","±®∏Ê±®∏Ê±®∏Ê‡¶ø"],
			eras: [{"name":"±®∏Ê±®∏Ê∞‡ßÄ±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶","start":null,"offset":0}],
			patterns: {
				d: "dd-MM-yyyy",
				D: "yyyy,MMMM dd, dddd",
				t: "tt h:mm",
				T: "tt h:mm:ss",
				f: "yyyy,MMMM dd, dddd tt h:mm",
				F: "yyyy,MMMM dd, dddd tt h:mm:ss",
				M: "dd MMMM",
				Y: "MMMM,yy"
			}
		}
	}
});

}( this ));
