/*
 * Globalize Culture bn
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "bn", "default", {
	name: "bn",
	englishName: "Bengali",
	nativeName: "±®∏Ê±®∏Ê±®∏Ê‡¶æ",
	language: "bn",
	numberFormat: {
		groupSizes: [3,2],
		percent: {
			pattern: ["-%n","%n"],
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["$ -n","$ n"],
			groupSizes: [3,2],
			symbol: "±®∏Ê¶æ"
		}
	},
	calendars: {
		standard: {
			"/": "-",
			":": ".",
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶∞"],
				namesAbbr: ["±®∏Ê±®∏Êø.","±®∏Ê±®∏ÊÆ.","±®∏Ê±®∏Ê±®∏Ê‡¶≤.","±®∏Ê±®∏Êß.","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê‡¶∞.","±®∏Ê±®∏Êø."],
				namesShort: ["‡¶∞","‡¶∏","‡¶Æ","‡¶¨","‡¶¨","‡¶∂","‡¶∂"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡ßÄ","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊÄ","±®∏Ê±®∏Ê±®∏Ê‡¶ö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶≤","±®∏Êßá","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡¶á","±®∏Ê±®∏Ê±®∏Ê‡¶ü","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê±®∏ÊßÅ.","±®∏Ê±®∏Ê±®∏Ê‡¶ö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê¶≤","±®∏Êßá","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡¶á","±®∏Ê¶ó.","±®∏Ê±®∏Ê±®∏Ê±®∏Êßá.","±®∏Ê±®∏Ê±®∏Ê‡ßã.","±®∏Ê±®∏Êá.","±®∏Ê±®∏Ê±®∏Ê.",""]
			},
			AM: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡¶®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡¶®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡¶®"],
			PM: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®"],
			patterns: {
				d: "dd-MM-yy",
				D: "dd MMMM yyyy",
				t: "HH.mm",
				T: "HH.mm.ss",
				f: "dd MMMM yyyy HH.mm",
				F: "dd MMMM yyyy HH.mm.ss",
				M: "dd MMMM"
			}
		}
	}
});

}( this ));
