/*
 * Globalize Culture ne-NP
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "ne-NP", "default", {
	name: "ne-NP",
	englishName: "Nepali (Nepal)",
	nativeName: "±®∏Ê±®∏Ê±®∏Ê±®∏Ê•Ä (±®∏Ê±®∏Ê±®∏Ê‡§≤)",
	language: "ne",
	numberFormat: {
		groupSizes: [3,2],
		"NaN": "nan",
		negativeInfinity: "-infinity",
		positiveInfinity: "infinity",
		percent: {
			pattern: ["-n%","n%"],
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["-$n","$n"],
			symbol: "±®∏Ê•Å"
		}
	},
	calendars: {
		standard: {
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Êπ‡•Ä±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞"],
				namesAbbr: ["±®∏Ê±®∏Ê§","±®∏Ê±®∏ÊÆ","±®∏Ê±®∏Ê±®∏Ê‡§≤","±®∏Ê±®∏Êß","±®∏Ê±®∏Êπ‡•Ä","±®∏Ê±®∏Ê±®∏Ê‡§∞","±®∏Ê±®∏Êø"],
				namesShort: ["‡§Ü","±®∏Ê•ã","‡§Æ","±®∏Ê•Å","±®∏Ê§ø","±®∏Ê•Å","‡§∂"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê‡•Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡•Ä","±®∏Ê±®∏Ê±®∏Ê‡§ö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§≤","±®∏Ê•á","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡§à","±®∏Ê±®∏Ê±®∏Ê‡§§","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê§∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""],
				namesAbbr: ["±®∏Ê§®","±®∏Ê±®∏Ê¨","±®∏Ê±®∏Ê±®∏Ê‡§ö","±®∏Ê±®∏Ê±®∏Ê±®∏Ê§≤","±®∏Ê•á","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡§à","±®∏Ê§ó","±®∏Ê±®∏Ê±®∏Ê‡§ü","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê≠","±®∏Ê±®∏Ê∏",""]
			},
			AM: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê•Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê•Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê•Ä"],
			PM: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê•Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê•Ä","±®∏Ê±®∏Ê±®∏Ê±®∏Ê•Ä"],
			eras: [{"name":"a.d.","start":null,"offset":0}],
			patterns: {
				Y: "MMMM,yyyy"
			}
		}
	}
});

}( this ));
