/*
 * Globalize Culture te
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "te", "default", {
	name: "te",
	englishName: "Telugu",
	nativeName: "±®∏Ê±®∏Ê±®∏Ê±®∏Ê±Å",
	language: "te",
	numberFormat: {
		groupSizes: [3,2],
		percent: {
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["$ -n","$ n"],
			groupSizes: [3,2],
			symbol: "±®∏Ê±Ç"
		}
	},
	calendars: {
		standard: {
			"/": "-",
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊÇ","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊÇ","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊÇ","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∞Ç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏ÊÇ"],
				namesAbbr: ["±®∏Ê±®∏Êø.","±®∏Ê±®∏ÊÆ.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Êß.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê‡∞∞.","±®∏Ê±®∏Êø."],
				namesShort: ["‡∞Ü","±®∏Ê±ã","±®∏Ê∞Ç","±®∏Ê±Å","±®∏Ê±Å","±®∏Ê±Å","‡∞∂"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê‡∞ø","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞ø","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êç","±®∏Ê±á","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±Å","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±ç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±ç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê‡∞ø","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞ø","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Êç","±®∏Ê±á","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±Å","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±ç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±ç","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê",""]
			},
			AM: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∞®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∞®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡∞®"],
			PM: ["±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê®"],
			patterns: {
				d: "dd-MM-yy",
				D: "dd MMMM yyyy",
				t: "HH:mm",
				T: "HH:mm:ss",
				f: "dd MMMM yyyy HH:mm",
				F: "dd MMMM yyyy HH:mm:ss",
				M: "dd MMMM"
			}
		}
	}
});

}( this ));
