/*
 * Globalize Culture pa
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "pa", "default", {
	name: "pa",
	englishName: "Punjabi",
	nativeName: "±®∏Ê±®∏Ê±®∏Ê±®∏Ê©Ä",
	language: "pa",
	numberFormat: {
		groupSizes: [3,2],
		percent: {
			groupSizes: [3,2]
		},
		currency: {
			pattern: ["$ -n","$ n"],
			groupSizes: [3,2],
			symbol: "±®∏Ê©Å"
		}
	},
	calendars: {
		standard: {
			"/": "-",
			firstDay: 1,
			days: {
				names: ["±®∏Ê±®∏Ê±®∏Ê‡®∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê®∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê∞","±®∏Ê©Ä±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê±®∏Ê‡®∞"],
				namesAbbr: ["±®∏Ê®§.","±®∏Ê±®∏ÊÆ.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê©Ä‡®∞.","±®∏Ê±®∏Ê±®∏Ê.","±®∏Ê±®∏Ê±®∏Ê±®∏Ê®∞."],
				namesShort: ["‡®ê","‡®∏","‡®Æ","‡®¨","‡®µ","‡®∂","‡®∂"]
			},
			months: {
				names: ["±®∏Ê±®∏Ê±®∏Ê‡©Ä","±®∏Ê±®∏Ê±®∏Ê‡©Ä","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê®≤","±®∏Ê®à","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡®à","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê‡®∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê®∞","±®∏Ê±®∏Ê±®∏Ê‡®∞","±®∏Ê±®∏Ê±®∏Ê‡®∞",""],
				namesAbbr: ["±®∏Ê±®∏Ê±®∏Ê‡©Ä","±®∏Ê±®∏Ê±®∏Ê‡©Ä","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê±®∏Ê®≤","±®∏Ê®à","±®∏Ê±®∏Ê®","±®∏Ê±®∏Ê±®∏Ê‡®à","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê‡®∞","±®∏Ê±®∏Ê±®∏Ê±®∏Ê®∞","±®∏Ê±®∏Ê±®∏Ê‡®∞","±®∏Ê±®∏Ê±®∏Ê‡®∞",""]
			},
			AM: ["±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê","±®∏Ê±®∏Ê±®∏Ê"],
			PM: ["±®∏Ê±®∏ÊÆ","±®∏Ê±®∏ÊÆ","±®∏Ê±®∏ÊÆ"],
			patterns: {
				d: "dd-MM-yy",
				D: "dd MMMM yyyy dddd",
				t: "tt hh:mm",
				T: "tt hh:mm:ss",
				f: "dd MMMM yyyy dddd tt hh:mm",
				F: "dd MMMM yyyy dddd tt hh:mm:ss",
				M: "dd MMMM"
			}
		}
	}
});

}( this ));
